name: CI

on:
  push:
    branches:
      - master
      - "hotfix/*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod
      - name: Checkout Cyber Punk site
        run: git clone https://github.com/TheSharpOwl/CyberpunkShowcase.git pages/cyberpunk # Add cyberpunk repo in the pages directory
      - name: Checkout Rock Paper Scissors site
        run: git clone https://github.com/TheSharpOwl/rock-paper-scissors.git pages/rps # Add rock-paper-scissors repo in the pages directory
      - name: Checkout Etch-a-Sketch site
        run: git clone https://github.com/TheSharpOwl/Etch-a-Sketch.git pages/drawing # Add etch-a-sketch repo in the pages directory
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        continue-on-error: true # This step will not fail the workflow
        run: bash tools/test.sh
